spring:
  messages:
    basename: i18n.bundle_${application.locale}

application:
  locale: ru_RU

questions:
  filepath: questions.csv

testing-settings:
  questionsCount: 5
  minCorrectAnswersForCredit: 2