DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    ID BIGINT IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(
    ID BIGINT IDENTITY PRIMARY KEY,
    VALUE TEXT NOT NULL,
    BOOK_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS "USER";
CREATE TABLE "USER"(
    ID BIGINT IDENTITY PRIMARY KEY,
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

ALTER TABLE BOOK ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);
ALTER TABLE COMMENT ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);