spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    show-sql: false

    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true